package cn.wthee.pcrtool.navigation
/**
 * 导航路径
 */
object NavRoute {
    const val HOME = "home"
    const val CHARACTER_LIST = "characterList"
    const val CHARACTER_DETAIL = "characterDetail"
    const val ALL_PICS = "allPics"
    const val ALL_PICS_TYPE = "allPicsType"
    const val CHARACTER_BASIC_INFO = "characterBasicInfo"
    const val CHARACTER_STORY_DETAIL = "characterStoryDetail"
    const val EQUIP_LIST = "equipList"
    const val EQUIP_DETAIL = "equipDetail"
    const val EXTRA_EQUIP_DETAIL = "exEquipDetail"
    const val RANK_EQUIP = "rankEquip"
    const val RANK_COMPARE = "rankCompare"
    const val EQUIP_COUNT = "equipCount"
    const val EQUIP_MATERIAL = "equipMaterial"
    const val TOOL_LEADER = "toolLeader"
    const val TOOL_GACHA = "toolGacha"
    const val TOOL_FREE_GACHA = "toolFreeGacha"
    const val TOOL_STORY_EVENT = "toolStoryEvent"
    const val TOOL_GUILD = "toolGuild"
    const val TOOL_CLAN = "toolClanBattle"
    const val TOOL_CLAN_BOSS_INFO = "toolClanBattleInfo"
    const val TOOL_PVP = "toolPvpSearch"
    const val TOOL_NEWS = "toolNews"
    const val TOOL_MOCK_GACHA = "toolMockGacha"
    const val MAIN_SETTINGS = "mainSettings"
    const val TWEET = "tweet"
    const val COMIC = "comic"
    const val ALL_SKILL = "allSkill"
    const val ALL_EQUIP = "allEquip"
    const val ATTR_COE = "attrCoe"
    const val UNIT_ID = "unitId"
    const val EQUIP_ID = "equipId"
    //最大rank
    const val MAX_RANK = "maxRank"
    //等级
    const val LEVEL = "level"
    //星级
    const val RARITY = "rarity"
    //rank
    const val RANK = "rank"
    //专用装备等级
    const val UNIQUE_EQUIP_LEVEL = "uniqueEquipLevel"
    //专用装备2等级
    const val UNIQUE_EQUIP_LEVEL2 = "uniqueEquipLevel2"
    const val TOOL_CLAN_Battle_ID = "toolClanBattleID"
    const val TOOL_CLAN_BOSS_INDEX = "toolClanBattleIndex"
    const val TOOL_CLAN_BOSS_MAX_PHASE = "toolClanBattleMaxPhase"
    const val TOOL_CLAN_BOSS_MIN_PHASE = "toolClanBattleMinPhase"
    const val SUMMON_DETAIL = "summonDetail"
    const val UNIT_TYPE = "unitType"
    const val TOOL_EQUIP_AREA = "toolArea"
    const val TOOL_MORE = "toolMore"
    const val TOOL_MORE_EDIT_MODE = "toolMoreEditMode"
    const val TOOL_BIRTHDAY = "toolBirthday"
    const val TOOL_CALENDAR_EVENT = "toolCalendarEvent"
    const val CHARACTER_SKILL_LOOP = "characterSkillLoop"
    const val TOOL_EXTRA_EQUIP = "toolExtraEquip"
    const val TOOL_EXTRA_EQUIP_UNIT = "toolExtraEquipUnit"
    const val TOOL_EQUIP_UNIT = "toolEquipUnit"
    const val EXTRA_EQUIP_CATEGORY = "toolExtraEquipCategory"
    const val EXTRA_EQUIP_DROP = "toolExtraEquipDrop"
    const val TOOL_TRAVEL_AREA = "toolExtraEquipTravelArea"
    const val TOOL_TRAVEL_AREA_DETAIL = "toolExtraEquipTravelAreaDetail"
    const val TRAVEL_QUEST_ID = "travelQuestId"
    const val CHARACTER_EXTRA_EQUIP_SLOT = "characterExtraEquipSlot"
    const val EVENT_ENEMY_DETAIL = "eventEnemyDetail"
    const val ENEMY_DETAIL = "enemyDetail"
    const val ENEMY_ID = "enemyId"
    const val PCR_WEBSITE = "pcrWebsite"
    const val TOOL_LEADER_TIER = "leaderTier"
    const val TOOL_ALL_QUEST = "allQuest"
    const val SEARCH_EQUIP_IDS = "searchEquipIds"
    const val UNIQUE_EQUIP_LIST = "uniqueEquipList"
    const val UNIQUE_EQUIP_DETAIL = "UniqueEquipDetail"

}
